# Question 2:-

# Write a program to print 'exists' if entered key already exists in the dictionary and print 'not exists' if the entered key does not exist.
# Example :-
# dict1={“name”:”Raju”, “marks”:56}
# Note :-
# If input is “name” then output will be “exist”
# If input is “class” then output will be “not exists”.


# FIRST METHOD............

# dict1={"name":"Raju","marks":56}
# for i in dict1:
#     # print(i)
#     user_input=input("enter the input")
#     if user_input in dict1:
#        print("exists")
#        break
#     else:
#        print("not exist")
#        break

# SECOND METHOD............

# dict1={"name":"Raju","marks":56}
# user_input=input("enter the input")
# if user_input in dict1:
#     print("exists")
# else:
#     print("not exist")

# THIRD METHOD............

# dict1={"name":"raju","marks":56}
# for x in dict1:
#     a=input("enter the input")
#     if a==x:
#         print("exist")
#         break
#     else:
#         print("not exist")
#         break

